select * 
from customer
limit 10;

--write a query to calculate the total revenue generated by male vs female customer?

select  customer_id, purchase_amount, 
        sum(purchase_amount) over (partition by gender,age order by purchase_amount desc) as total_revenue
from    customer;

-- write a query to find customer used discount but still spent more then the avg purchase amount

with avg_purchase as(select  avg(purchase_amount) as avg_amount
                      from customer)
select customer_id,
       purchase_amount
from customer,avg_purchase
where discount_applied = 'yes'
  and purchase_amount >= avg_amount;

--write a query to find the top 5 products with the highest avg review rating

select item_purchased, round(avg(review_rating :: numeric),2) as avg_rating
from   customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- write a query to compare the avg purchase amount between standard and express shipping

select shipping_type, round(avg(purchase_amount),2)
from   customer
where shipping_type in ('standard','express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
       count(customer_id) as total_customer,
	   round(avg(purchase_amount),2) as avg_spend,
	   round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from   customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer)

select customer_segment,count(*) as "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
select customer_id, item_purchased,product_rank
from (select customer_id, item_purchased,
      dense_rank() over (partition by category order by customer_id )as product_rank
      from customer)
where product_rank <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
       COUNT(customer_id) AS repeat_buyers
from customer
where previous_purchases > 5
group by  subscription_status;

--Q10. What is the revenue contribution of each age group? 
select distinct(revenue_per_age), age
from(select age,
       SUM(purchase_amount) over (partition by age) as revenue_per_age
	 from customer)
order by age;

